### ISSUE TITLE
Домашка №3 (ООП)

### ISSUE THREAD

**Issue by kottans-net** [agni90/kottansHomeTasks#4]
Предлагаем вам выполнить домашку по ООП https://github.com/Zaknafeyn/OOP.Task

**Comment by agni90** [comment]
The issue was resolved. See here: https://github.com/agni90/kottansHomeTasks/tree/master/HomeTask_%233/OOP.Task-master

**Comment by kottans-net** [comment]
Проверено.
Хорошая работа, есть замечание:
метод Move() во всех классах одинаковый, его можно вынести вынести в базовый класс. 

Удобно, что есть конструкторы которые принимают необходимые параметры и конвертируют их в структуру IDictionary
